# Generated by Django 4.2.7 on 2026-02-01 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500, verbose_name='Token')),
                ('expires_at', models.DateTimeField(verbose_name='Expira en')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_tokens', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Token de video',
                'verbose_name_plural': 'Tokens de videos',
                'db_table': 'video_tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
