# Generated by Django 4.2.7 on 2026-02-01 17:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('short_description', models.CharField(max_length=300, verbose_name='Descripción corta')),
                ('cover_image', models.ImageField(upload_to='courses/covers/', verbose_name='Imagen de portada')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('difficulty', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='beginner', max_length=20, verbose_name='Dificultad')),
                ('duration_hours', models.PositiveIntegerField(default=0, verbose_name='Duración (horas)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('video_id', models.CharField(help_text='ID del video en Cloudflare Stream', max_length=200, verbose_name='ID del video')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Duración (minutos)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_preview', models.BooleanField(default=False, verbose_name='Vista previa gratis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Lección',
                'verbose_name_plural': 'Lecciones',
                'db_table': 'lessons',
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'db_table': 'modules',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Completada')),
                ('progress_percentage', models.PositiveIntegerField(default=0, verbose_name='Porcentaje de progreso')),
                ('last_watched_at', models.DateTimeField(auto_now=True, verbose_name='Última visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Progreso de lección',
                'verbose_name_plural': 'Progresos de lecciones',
                'db_table': 'lesson_progress',
            },
        ),
    ]
