# Generated by Django 4.2.7 on 2026-02-26 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='courses/documents/', verbose_name='Archivo')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre visible')),
                ('file_type', models.CharField(blank=True, max_length=20, verbose_name='Tipo')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='Tamaño (bytes)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Documento de lección',
                'verbose_name_plural': 'Documentos de lección',
                'db_table': 'lesson_documents',
                'ordering': ['lesson', 'order', 'name'],
            },
        ),
    ]
