# Generated by Django 4.2.7 on 2026-02-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lessondocument'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessondocument',
            options={'ordering': ['lesson', 'created_at'], 'verbose_name': 'Documento de lección', 'verbose_name_plural': 'Documentos de lecciones'},
        ),
        migrations.RemoveField(
            model_name='lessondocument',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='lessondocument',
            name='name',
        ),
        migrations.RemoveField(
            model_name='lessondocument',
            name='order',
        ),
        migrations.RemoveField(
            model_name='lessondocument',
            name='size_bytes',
        ),
        migrations.AddField(
            model_name='lessondocument',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='lessondocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida'),
        ),
        migrations.AlterField(
            model_name='lessondocument',
            name='file',
            field=models.FileField(upload_to='lessons/documents/', verbose_name='Archivo'),
        ),
    ]
