# Generated by Django 4.2.7 on 2026-02-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lessondocument_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video'), ('document', 'Documento')], default='video', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_id',
            field=models.CharField(blank=True, help_text='ID del video en Cloudflare Stream', max_length=200, verbose_name='ID del video'),
        ),
    ]
