# Generated by Django 4.2.7 on 2026-02-01 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de compra')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de expiración')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Acceso a curso',
                'verbose_name_plural': 'Accesos a cursos',
                'db_table': 'course_accesses',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_payment_id', models.CharField(max_length=100, unique=True, verbose_name='ID de pago MP')),
                ('mp_preference_id', models.CharField(blank=True, max_length=100, verbose_name='ID de preferencia MP')),
                ('mp_merchant_order_id', models.CharField(blank=True, max_length=100, verbose_name='ID de orden MP')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Estado')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Método de pago')),
                ('payment_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de pago')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Datos crudos')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='courses.course')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
