# Generated by Django 4.2.7 on 2026-02-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='mp_payment_id',
            field=models.CharField(blank=True, default='', max_length=100, unique=True, verbose_name='ID de pago MP'),
        ),
    ]
