# Generated by Django 4.2.14 on 2026-04-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_transaction_mp_payment_id_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='mp_payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID de pago MP'),
        ),
    ]
